### ISSUE TITLE
Issue with filtering black photo

### ISSUE THREAD

**Issue by emrememil** [iamutkarshtiwari/Ananas#85]
App crashes while applying any filter to solid black image.

**Log:** 
Error: A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7e51cf4f44 in tid 10742 (RxComputationTh), pid 10254 (udapper.android)

sample photo: https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Black_flag.svg/750px-Black_flag.svg.png

**Comment by iamutkarshtiwari** [comment]
Thanks for reporting this. 
Seems like the extension of this image is `.svg`. Could you cross-check because the library supports only non-svg images.

**Comment by emrememil** [comment]
The same problem is experienced with photos with `.png` or `.jpeg` extensions. Thank you for your interest

**Comment by iamutkarshtiwari** [comment]
Could you please attach all those photos you are facing this issue with? I'll try to debug and fix it.

**Comment by emrememil** [comment]
Sample image;
![images](https://user-images.githubusercontent.com/23477055/107186094-b3897980-69f4-11eb-9f84-aca2fc03d6b0.png)

**Comment by iamutkarshtiwari** [comment]
Thanks! I was able to reproduce it. Seems an interesting issue. Let me look into it.

**Comment by emrememil** [comment]
Yes it is quite interesting. Thank you for your interest.

**Comment by iamutkarshtiwari** [comment]
I looked into this issue and it seems like that there is this edge case in the JNI library used for image transformation. Since it's an extreme case which will hardly occur and I also need to re-factor, recompile and redeploy the native .so files, it's quite an overkill.
I'll re-consider it if this issue is recurrent. 
Thanks for notifying though!
