### ISSUE TITLE
Android 11(R) target SDK migration

### ISSUE THREAD

**Issue by farrakhj** [iamutkarshtiwari/Ananas#87]
Hello everyone,

Anyone started at migration of code to Android 11(R) target SDK? For Android 10(Q) we are using Manifest Tag android:requestLegacyExternalStorage="true" but for Android 11(R) target SDK it will not work.

Regards,
Farrakh

**Comment by iamutkarshtiwari** [comment]
Thank you for reporting this @farrakhj

**Comment by farrakhj** [comment]
@iamutkarshtiwari Any update at this thread?

**Comment by rahat14** [comment]
@farrakhj 
How did u got it for andorid 10 i am having this -> 
 https://github.com/iamutkarshtiwari/Ananas/issues/89

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.

**Comment by farrakhj** [comment]
Can you kindly explicitly explain the change for #87 issue?

**Comment by iamutkarshtiwari** [comment]
@farrakhj Until previous versions, I was using legacy way of loading images from mediastore database into a custom grid view. Since Android enforced scoped storage from Android 10 onwards, Ananas users started experiencing crash when picking images from gallery on devices >= Android 10. 

That's why you had to use `android:requestExternalLegacyStorage` to make it work on 10 which was available shortly for backward compatibility and was removed later in 11.

**Comment by farrakhj** [comment]
As android:requestExternalLegacyStorage is removed from Android 11 and after 1st of May we will not be able to upload apk/aab to play console. So after removing android:requestExternalLegacyStorage will Ananas work on android 10 and onwards? If users not experience crash than what is the change in code?

**Comment by iamutkarshtiwari** [comment]
@farrakhj I have tested the latest version on Android 10 and 11 without `android:requestExternalLegacyStorage`. Works just fine. I'd recommend you to try as well。
